# Site settings
title: Onur ÅentÃ¼re
description: >
    Hello! ğŸ³ I'm Onur Senture. Nebuu, Harf Marf ve birÃ§ok yenilikÃ§i projenin Ã¶ncÃ¼lÃ¼ÄŸÃ¼nÃ¼ yapmakta olan Orkestra'nÄ±n kurucu ortaÄŸÄ± ve Ã¼rÃ¼n tasarÄ±mcÄ±sÄ±yÄ±m. AynÄ± zamanda PrimeFaces'da tasarÄ±m uzmanÄ± olarak Ã§alÄ±ÅŸmaktayÄ±m.
author: Onur ÅentÃ¼re
email: onur@orkestrayazilim.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onursenture.github.com" # the base hostname & protocol for your site
twitter_username: w00f
github_username:  onursenture

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
